name: 'zsh Action'
description: 'Execute commands in a properly initialized zsh environment'
inputs:
  run:
    description: 'Commands to run in ZSh'
    required: true
  as_user:
    description: 'User to run the commands as (optional)'
    required: false
    default: ""
outputs:
  exit_code:
    description: 'The exit code of the commands'
    value: ${{ steps.zsh-run.outputs.exit_code }}
runs:
  using: 'composite'
  steps:
    - name: Execute commands in zsh
      id: zsh-run
      shell: bash
      run: |
        # Write user commands to a temp script
        TEMP_SCRIPT=$(mktemp)
        trap 'rm -f "${TEMP_SCRIPT}"' EXIT
        echo "${{ inputs.run }}" > "${TEMP_SCRIPT}"

        ZSH_COMMAND='[ -f ~/.zshrc ] && source ~/.zshrc; source '"${TEMP_SCRIPT}"
        if [ -n "${{ inputs.as_user }}" ]; then
          chmod o+r "${TEMP_SCRIPT}"
          sudo -u "${{ inputs.as_user }}" zsh -c "${ZSH_COMMAND}"
        else
          zsh -c "${ZSH_COMMAND}"
        fi
        
        # Store the exit code as an output
        echo "exit_code=$?" >> $GITHUB_OUTPUT
